pre-commit:
  parallel: true
  jobs:
  - name: ruff
    tags:
    - python
    - lint
    glob: "*.py"
    stage_fixed: true
    group:
      parallel: false
      jobs:
      - run: uv run ruff check --fix {staged_files}
      - run: uv run ruff format {staged_files}
  - name: ty
    tags:
    - python
    - lint
    glob: "*.py"
    run: uv run ty check {staged_files}
  - name: mypy
    tags:
    - python
    - lint
    glob: "*.py"
    run: uv run mypy examples/ src/

pre-push:
  parallel: true
  jobs:
  - name: ruff
    tags:
    - python
    - lint
    group:
      parallel: false
      jobs:
      - run: uv run ruff check
      - run: uv run ruff format
  - name: ty
    tags:
    - python
    - lint
    glob: "*.py"
    run: uv run ty check
  - name: mypy
    tags:
    - python
    - lint
    glob: "*.py"
    run: uv run mypy examples/ src/
  - name: License checks
    tags:
    - licenses
    group:
      parallel: true
      jobs:
      - name: External license check
        run: uv run licensecheck --zero
      - name: License comments
        run: ./.tools/check-license-comments.sh
