ARG CHECKMK_VERSION=2.4.0p12
FROM checkmk/check-mk-raw:${CHECKMK_VERSION}

ENV DEBIAN_FRONTEND=noninteractive

COPY agent-integration/watchpost_collect /usr/local/bin/watchpost_collect
COPY agent-integration/watchpost_check /usr/local/bin/watchpost_check

RUN set -ex ;\
    chmod +x /usr/local/bin/watchpost_check ;\
    chmod +x /usr/local/bin/watchpost_collect ;\
    mkdir /omd/versions/default/lib/check_mk/plugins/watchpost/ ;\
    :

COPY watchpost-plugin/ /omd/versions/default/lib/check_mk/plugins/watchpost/
